### ISSUE TITLE
setupControllerForExportedBuilder doesn't exist?

### ISSUE THREAD

**Issue by subtleGradient** [hediet/node-reload#9]
https://github.com/hediet/node-reload/blob/4f6f852ee84ec1976544fd6bf3b149d892fe2c49/examples/puppeteer/src/knuddels.ts#L5

Trying to get your puppeteer example working locally, but `setupControllerForExportedBuilder` and `installUpdateReconciler` don't exist :(

**Comment by hediet** [comment]
This `knuddels.ts` example was never meant to be pushed, it seems I did that by accident.

Look at https://github.com/hediet/node-reload/blob/master/examples/src/moodle.entry.ts for a working puppeteer example (I updated it in my last commit to work with moodles again)!

Sadly the currently published Live Debug extension does not work anymore with the most recent VS Code, since they changed the debug adapter name from `node` to `pwa-node`. If you install the VS Code extension and replace the first occurence of `"node"` with `"pwa-node"` it works though:

![image](https://user-images.githubusercontent.com/2931520/90127756-fb8d5380-dd65-11ea-9774-00da2531cb37.png)

I already have ideas how to make everything better (both node-reload and Live Debug), but I'm missing the time to do it.
Ideally, I would like node-reload to be non-invasive and just a VS Code extension.
